services:
  - type: web
    name: caneorbit-db
    runtime: docker
    repo: https://github.com/seu-usuario/caneorbit-backend-java-csharp
    dockerfilePath: ./Dockerfile.db
    envVars:
      - key: ORACLE_PASSWORD
        value: oracle123

  - type: web
    name: caneorbit-api-csharp
    runtime: docker
    repo: https://github.com/seu-usuario/caneorbit-backend-java-csharp
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ConnectionStrings__OracleConnection
        value: User Id=SYSTEM;Password=oracle123;Data Source=caneorbit-db:1521/XE
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: web
    name: caneorbit-api-java
    runtime: docker
    repo: https://github.com/seu-usuario/caneorbit-backend-java-csharp
    dockerfilePath: ./caneorbitJava/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:oracle:thin:@caneorbit-db:1521/XE
      - key: SPRING_DATASOURCE_USERNAME
        value: SYSTEM
      - key: SPRING_DATASOURCE_PASSWORD
        value: oracle123
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: validate