services:
  - type: web
    name: caneorbit-api-csharp-prod
    runtime: docker
    repo: https://github.com/FIAP-CANEORBIT/caneorbis-api-dotnet
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: caneorbit-db-prod
          property: connectionString
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: web
    name: caneorbit-api-java-prod
    runtime: docker
    repo: https://github.com/FIAP-CANEORBIT/caneorbis-api-dotnet
    dockerfilePath: ./caneorbitJava/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: caneorbit-db-prod
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: caneorbit-db-prod
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: caneorbit-db-prod
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

databases:
  - name: caneorbit-db-prod
    plan: free
    databaseName: caneorbit_db
    user: caneorbit_user