# Nome da Aplicação
spring.application.name=caneorbit

# Oracle DB - Banco local
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=SYSTEM
spring.datasource.password=oracle123

# JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
api.security.token.secret=aH7!xP9$mR4&jK2@vC5bN8zL3qW6fD1*gT9yU0sI4oQ7eL2kZ8wX5cV3nJ1mB6hG
api.security.token.issuer=caneorbit-api