// <auto-generated />
using System;
using CaneOrbis.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CaneOrbis.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603185222_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaneOrbis.Api.Models.DadoSatelite", b =>
                {
                    b.Property<int>("IdDadoSatelite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DADO_SATELITE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDadoSatelite"));

                    b.Property<string>("DsCondicaoClima")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DS_CONDICAO_CLIMA");

                    b.Property<DateTime>("DtColeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DT_COLETA")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdDispositivo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DISPOSITIVO");

                    b.Property<decimal?>("VlNdvi")
                        .HasColumnType("NUMBER(10,4)")
                        .HasColumnName("VL_NDVI");

                    b.Property<decimal?>("VlPrecipitacao")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("VL_PRECIPITACAO");

                    b.Property<decimal?>("VlTemperaturaAr")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("VL_TEMPERATURA_AR");

                    b.HasKey("IdDadoSatelite");

                    b.HasIndex("IdDispositivo");

                    b.ToTable("T_ORB_DADO_SATELITE", (string)null);
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.DispositivoIot", b =>
                {
                    b.Property<int>("IdDispositivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DISPOSITIVO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDispositivo"));

                    b.Property<string>("DsMacAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("NVARCHAR2(17)")
                        .HasColumnName("DS_MAC_ADDRESS");

                    b.Property<string>("DsStatusDispositivo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("ATIVO")
                        .HasColumnName("DS_STATUS_DISPOSITIVO");

                    b.Property<DateTime>("DtInstalacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("DT_INSTALACAO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<int>("IdTalhao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TALHAO");

                    b.Property<string>("NmApelido")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NM_APELIDO");

                    b.Property<decimal?>("VlLatitude")
                        .HasColumnType("NUMBER(10,8)")
                        .HasColumnName("VL_LATITUDE");

                    b.Property<decimal?>("VlLongitude")
                        .HasColumnType("NUMBER(11,8)")
                        .HasColumnName("VL_LONGITUDE");

                    b.HasKey("IdDispositivo");

                    b.HasIndex("DsMacAddress")
                        .IsUnique();

                    b.HasIndex("IdTalhao");

                    b.ToTable("T_ORB_DISPOSITIVO_IOT", (string)null);
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.LeituraSensor", b =>
                {
                    b.Property<int>("IdLeitura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LEITURA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLeitura"));

                    b.Property<DateTime>("DtLeitura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DT_LEITURA")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdDispositivo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DISPOSITIVO");

                    b.Property<decimal?>("VlPhSolo")
                        .HasColumnType("NUMBER(4,2)")
                        .HasColumnName("VL_PH_SOLO");

                    b.Property<decimal>("VlTemperatura")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("VL_TEMPERATURA");

                    b.Property<decimal>("VlUmidadeSolo")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("VL_UMIDADE_SOLO");

                    b.HasKey("IdLeitura");

                    b.HasIndex("IdDispositivo");

                    b.ToTable("T_ORB_LEITURA_SENSOR", (string)null);
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.Propriedade", b =>
                {
                    b.Property<int>("IdPropriedade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PROPRIEDADE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPropriedade"));

                    b.Property<string>("DsLocalizacao")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("DS_LOCALIZACAO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("NmPropriedade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_PROPRIEDADE");

                    b.Property<decimal?>("VlAreaHectare")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("VL_AREA_HECTARE");

                    b.HasKey("IdPropriedade");

                    b.HasIndex("IdUsuario");

                    b.ToTable("T_ORB_PROPRIEDADE", (string)null);
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.Talhao", b =>
                {
                    b.Property<int>("IdTalhao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TALHAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTalhao"));

                    b.Property<string>("DsCultura")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasDefaultValue("CANA_DE_ACUCAR")
                        .HasColumnName("DS_CULTURA");

                    b.Property<string>("DsTipoSolo")
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("DS_TIPO_SOLO");

                    b.Property<int>("IdPropriedade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PROPRIEDADE");

                    b.Property<string>("NmTalhao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_TALHAO");

                    b.Property<decimal?>("VlAreaHectare")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("VL_AREA_HECTARE");

                    b.HasKey("IdTalhao");

                    b.HasIndex("IdPropriedade");

                    b.ToTable("T_ORB_TALHAO", (string)null);
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("DsSenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DS_SENHA_HASH");

                    b.Property<DateTime>("DtCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DT_CADASTRO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NmUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_USUARIO");

                    b.HasKey("IdUsuario");

                    b.HasIndex("DsEmail")
                        .IsUnique();

                    b.ToTable("T_ORB_USUARIO", (string)null);
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.DadoSatelite", b =>
                {
                    b.HasOne("CaneOrbis.Api.Models.DispositivoIot", "DispositivoIot")
                        .WithMany("DadosSatelite")
                        .HasForeignKey("IdDispositivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DispositivoIot");
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.DispositivoIot", b =>
                {
                    b.HasOne("CaneOrbis.Api.Models.Talhao", "Talhao")
                        .WithMany("DispositivosIot")
                        .HasForeignKey("IdTalhao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Talhao");
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.LeituraSensor", b =>
                {
                    b.HasOne("CaneOrbis.Api.Models.DispositivoIot", "DispositivoIot")
                        .WithMany("LeiturasSensor")
                        .HasForeignKey("IdDispositivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DispositivoIot");
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.Propriedade", b =>
                {
                    b.HasOne("CaneOrbis.Api.Models.Usuario", "Usuario")
                        .WithMany("Propriedades")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.Talhao", b =>
                {
                    b.HasOne("CaneOrbis.Api.Models.Propriedade", "Propriedade")
                        .WithMany("Talhoes")
                        .HasForeignKey("IdPropriedade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.DispositivoIot", b =>
                {
                    b.Navigation("DadosSatelite");

                    b.Navigation("LeiturasSensor");
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.Propriedade", b =>
                {
                    b.Navigation("Talhoes");
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.Talhao", b =>
                {
                    b.Navigation("DispositivosIot");
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.Usuario", b =>
                {
                    b.Navigation("Propriedades");
                });
#pragma warning restore 612, 618
        }
    }
}
