// <auto-generated />
using System;
using CaneOrbis.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CaneOrbis.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603170921_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaneOrbis.Api.Models.DadoSatelite", b =>
                {
                    b.Property<int>("IdDadoSatelite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DADO_SATELITE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDadoSatelite"));

                    b.Property<string>("DsCondicaoClima")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DS_CONDICAO_CLIMA");

                    b.Property<DateTime>("DtColeta")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DT_COLETA");

                    b.Property<int>("IdDispositivo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DISPOSITIVO");

                    b.Property<decimal?>("VlNdvi")
                        .HasColumnType("NUMBER(10,4)")
                        .HasColumnName("VL_NDVI");

                    b.Property<decimal?>("VlPrecipitacao")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("VL_PRECIPITACAO");

                    b.Property<decimal?>("VlTemperaturaAr")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("VL_TEMPERATURA_AR");

                    b.HasKey("IdDadoSatelite");

                    b.HasIndex("IdDispositivo");

                    b.ToTable("T_ORB_DADO_SATELITE", (string)null);
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.DispositivoIot", b =>
                {
                    b.Property<int>("IdDispositivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DISPOSITIVO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDispositivo"));

                    b.HasKey("IdDispositivo");

                    b.ToTable("T_ORB_DISPOSITIVO_IOT", (string)null);
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.LeituraSensor", b =>
                {
                    b.Property<int>("IdLeitura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LEITURA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLeitura"));

                    b.Property<DateTime>("DtLeitura")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DT_LEITURA");

                    b.Property<int>("IdDispositivo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DISPOSITIVO");

                    b.Property<decimal?>("VlPhSolo")
                        .HasColumnType("NUMBER(4,2)")
                        .HasColumnName("VL_PH_SOLO");

                    b.Property<decimal>("VlTemperatura")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("VL_TEMPERATURA");

                    b.Property<decimal>("VlUmidadeSolo")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("VL_UMIDADE_SOLO");

                    b.HasKey("IdLeitura");

                    b.HasIndex("IdDispositivo");

                    b.ToTable("T_ORB_LEITURA_SENSOR", (string)null);
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.DadoSatelite", b =>
                {
                    b.HasOne("CaneOrbis.Api.Models.DispositivoIot", "DispositivoIot")
                        .WithMany("DadosSatelite")
                        .HasForeignKey("IdDispositivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DispositivoIot");
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.LeituraSensor", b =>
                {
                    b.HasOne("CaneOrbis.Api.Models.DispositivoIot", "DispositivoIot")
                        .WithMany("LeiturasSensor")
                        .HasForeignKey("IdDispositivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DispositivoIot");
                });

            modelBuilder.Entity("CaneOrbis.Api.Models.DispositivoIot", b =>
                {
                    b.Navigation("DadosSatelite");

                    b.Navigation("LeiturasSensor");
                });
#pragma warning restore 612, 618
        }
    }
}
